import { useState } from "react";
import jsPDF from "jspdf";
import { Download, Link as LinkIcon, Share2, Zap, Heart } from "lucide-react";

export default function QuickActions({ userData, repos }) {
  const [activeIndex, setActiveIndex] = useState(null);
  const [toast, setToast] = useState("");

  const showToast = (msg) => {
    setToast(msg);
    setTimeout(() => setToast(""), 2200);
  };

  const actions = [
    { icon: Download, label: "Export PDF", desc: "Download a one-page profile report" },
    { icon: Heart, label: "Save profile", desc: "Add to favorites", disabled: true },
    { icon: LinkIcon, label: "Copy link", desc: "Copy this GitHub URL" },
    { icon: Share2, label: "Share profile", desc: "Share with friends" },
  ];

  const exportPDF = () => {
    if (!userData) return showToast("Search a profile first.");
    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const left = 48, right = 547;
    let y = 56;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("GitHub Profile Report", left, y);
    y += 8;
    doc.setDrawColor(147, 51, 234);
    doc.setLineWidth(1.4);
    doc.line(left, y, right, y);
    y += 26;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.text(userData.name || userData.login, left, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    doc.setTextColor(120, 120, 120);
    doc.text(`@${userData.login}`, left, y + 15);
    doc.setTextColor(20, 20, 20);
    y += 34;

    const field = (label, value) => {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10.5);
      doc.text(label, left, y);
      doc.setFont("helvetica", "normal");
      doc.text(String(value ?? "—"), left + 110, y);
      y += 19;
    };

    field("Followers", userData.followers);
    field("Following", userData.following);
    field("Public Repos", userData.public_repos);
    field("Location", userData.location || "Not specified");
    field("Company", userData.company || "Not specified");
    field("GitHub URL", userData.html_url);

    y += 14;
    doc.setDrawColor(225, 225, 225);
    doc.setLineWidth(0.7);
    doc.line(left, y, right, y);
    y += 26;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text("Top Repositories", left, y);
    y += 20;

    (repos || []).slice(0, 5).forEach((repo) => {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10.5);
      doc.text(repo.name, left, y);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(120, 120, 120);
      doc.text(`${repo.stargazers_count} stars · ${repo.forks_count} forks`, left + 220, y);
      doc.setTextColor(20, 20, 20);
      y += 18;
    });

    doc.setFontSize(8.5);
    doc.setTextColor(160, 160, 160);
    doc.text("Generated by GitScope", left, 800);
    doc.save(`${userData.login}-profile.pdf`);
  };

  const copyLink = async () => {
    if (!userData) return showToast("Search a profile first.");
    try {
      if (navigator.clipboard && window.isSecureContext) {
        await navigator.clipboard.writeText(userData.html_url);
      } else {
        const textarea = document.createElement("textarea");
        textarea.value = userData.html_url;
        textarea.style.position = "fixed";
        textarea.style.opacity = "0";
        document.body.appendChild(textarea);
        textarea.focus();
        textarea.select();
        document.execCommand("copy");
        document.body.removeChild(textarea);
      }
      showToast("GitHub URL copied!");
    } catch {
      showToast("Couldn't copy link.");
    }
  };

  const shareProfile = async () => {
    if (!userData) return showToast("Search a profile first.");
    try {
      if (navigator.share) {
        await navigator.share({
          title: userData.login,
          text: "Check out this GitHub profile",
          url: userData.html_url,
        });
      } else {
        await copyLink();
      }
    } catch (err) {
      if (err.name !== "AbortError") {
        await copyLink();
      }
    }
  };

  const handleAction = (label) => {
    if (label === "Export PDF") exportPDF();
    if (label === "Copy link") copyLink();
    if (label === "Share profile") shareProfile();
  };

  return (
    <section className="qa-card">
      <div className="sec-header">
        <div className="sec-header-left">
          <div className="sec-icon">
            <Zap size={18} />
          </div>
          <div>
            <h2 className="sec-title">Quick actions</h2>
            <p className="sec-sub">Instant profile operations</p>
          </div>
        </div>
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: 11 }}>
        {actions.map((action, index) => {
          const Icon = action.icon;
          return (
            <button
              key={action.label}
              type="button"
              disabled={action.disabled}
              className="qa-item"
              onClick={() => !action.disabled && handleAction(action.label)}
              onTouchStart={() => !action.disabled && setActiveIndex(index)}
              onMouseEnter={() => !action.disabled && setActiveIndex(index)}
              onMouseLeave={() => setActiveIndex(null)}
            >
              <span className="qa-shine" />
              <span className="qa-icon-wrap">
                <Icon size={18} />
              </span>
              <span style={{ textAlign: "left" }}>
                <p className="qa-label">{action.label}</p>
                <p className="qa-desc">{action.desc}</p>
              </span>
              <span className="qa-arrow">→</span>
            </button>
          );
        })}
      </div>

      <div className="qa-tip">
        <strong style={{ color: "var(--accent-from)" }}>Pro tip:</strong> export
        a clean one-page PDF report, share the profile, or copy the GitHub link
        in one click.
      </div>

      {toast && (
        <div
          style={{
            marginTop: 12,
            padding: "8px 12px",
            borderRadius: 10,
            background: "#0f172a",
            color: "#fff",
            fontSize: "0.8rem",
            textAlign: "center",
          }}
        >
          {toast}
        </div>
      )}
    </section>
  );}